"""empty message

Revision ID: 4f5fab7b38b2
Revises: 0fa4e6d85045
Create Date: 2018-04-06 22:21:30.732282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5fab7b38b2'
down_revision = '0fa4e6d85045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('shown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'shown')
    # ### end Alembic commands ###
