"""empty message

Revision ID: 9352ee534571
Revises: 2e84981827f3
Create Date: 2019-02-04 11:28:49.669995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9352ee534571'
down_revision = '2e84981827f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('shown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'shown')
    # ### end Alembic commands ###
